
STRINGS = {
    "es": {
        # Sidebar
        "app_subtitle":     "Java Edition",
        "nav_play":         "  Jugar",
        "nav_config":       "  Configuracion",
        "nav_about":        "  Acerca de",
        "status_ready":     "Listo",

        # Play tab
        "play_title":       "Selecciona una version",
        "play_reload":      "  Recargar",
        "play_show":        "MOSTRAR:",
        "play_release":     "Releases",
        "play_snapshot":    "Snapshots",
        "play_beta":        "Betas",
        "play_alpha":       "Alphas",
        "play_btn":         "  JUGAR  ",
        "play_loading":     "  Cargando lista de versiones...",
        "play_loaded":      "{n} versiones cargadas",
        "play_no_results":  "  Sin resultados — activa mas filtros",
        "play_warn_title":  "Sin version",
        "play_warn_msg":    "Selecciona una version primero.",
        "play_connecting":  "Conectando con Mojang...",
        "play_installing":  "Instalando {v}...",
        "play_running":     "Minecraft {v} en ejecucion",
        "play_preparing":   "Preparando...",
        "err_net_title":    "Error de red",
        "err_launch_title": "Error al lanzar",

        # Config tab
        "cfg_title":        "Configuracion",
        "cfg_subtitle":     "Ajustes del launcher y del juego",
        "cfg_sec_account":  "Perfil",
        "cfg_sec_account_s":"Modo offline",
        "cfg_sec_java":     "Java y Rendimiento",
        "cfg_sec_paths":    "Rutas del juego",
        "cfg_sec_versions": "Versiones visibles en el launcher",
        "cfg_sec_lang":     "Idioma / Language",
        "cfg_username":     "Nombre de usuario",
        "cfg_username_h":   "Nombre que aparece en el juego",
        "cfg_rammin":       "RAM minima",
        "cfg_rammin_h":     "Ej: 512M, 1G",
        "cfg_rammax":       "RAM maxima",
        "cfg_rammax_h":     "Ej: 2G, 4G, 8G",
        "cfg_java":         "Ruta de Java",
        "cfg_java_h":       "Dejar vacio para deteccion automatica",
        "cfg_gamedir":      "Directorio de Minecraft",
        "cfg_gamedir_h":    "Carpeta donde se instalan las versiones",
        "cfg_browse":       " Examinar ",
        "cfg_save":         "Guardar cambios",
        "cfg_saved_title":  "Guardado",
        "cfg_saved_msg":    "Configuracion guardada correctamente.",
        "cfg_warn_restart": "Reinicia el launcher para aplicar el nuevo idioma.",
        "cfg_activated":    "Activado",
        "cfg_deactivated":  "Desactivado",
        "cfg_offline_warn": "Para cuentas Microsoft usa el launcher oficial.",
        "cfg_show_rel":     "Releases",
        "cfg_show_rel_s":   "Versiones estables oficiales",
        "cfg_show_snap":    "Snapshots",
        "cfg_show_snap_s":  "Versiones de desarrollo",
        "cfg_show_beta":    "Betas",
        "cfg_show_beta_s":  "Versiones beta antiguas",
        "cfg_show_alph":    "Alphas",
        "cfg_show_alph_s":  "Versiones alpha antiguas",

        # About tab
        "about_subtitle":   "Launcher no oficial de Minecraft Java Edition",
        "about_version":    "Version 2.0  |  Python + minecraft-launcher-lib",
        "about_f1_t":       "Versiones",
        "about_f1_d":       "Release, Snapshot\nBeta y Alpha",
        "about_f2_t":       "Descarga",
        "about_f2_d":       "Assets y librerias\nauto desde Mojang",
        "about_f3_t":       "RAM",
        "about_f3_d":       "Totalmente\nconfigurable",
        "about_f4_t":       "Java",
        "about_f4_d":       "Deteccion\nautomatica",
        "about_disclaimer": "No afiliado con Mojang Studios ni Microsoft Corporation.",
    },

    "en": {
        # Sidebar
        "app_subtitle":     "Java Edition",
        "nav_play":         "  Play",
        "nav_config":       "  Settings",
        "nav_about":        "  About",
        "status_ready":     "Ready",

        # Play tab
        "play_title":       "Select a version",
        "play_reload":      "  Reload",
        "play_show":        "SHOW:",
        "play_release":     "Releases",
        "play_snapshot":    "Snapshots",
        "play_beta":        "Betas",
        "play_alpha":       "Alphas",
        "play_btn":         "  PLAY  ",
        "play_loading":     "  Loading version list...",
        "play_loaded":      "{n} versions loaded",
        "play_no_results":  "  No results — enable more filters",
        "play_warn_title":  "No version",
        "play_warn_msg":    "Please select a version first.",
        "play_connecting":  "Connecting to Mojang...",
        "play_installing":  "Installing {v}...",
        "play_running":     "Minecraft {v} is running",
        "play_preparing":   "Preparing...",
        "err_net_title":    "Network error",
        "err_launch_title": "Launch error",

        # Config tab
        "cfg_title":        "Settings",
        "cfg_subtitle":     "Launcher and game settings",
        "cfg_sec_account":  "Profile",
        "cfg_sec_account_s":"Offline mode",
        "cfg_sec_java":     "Java & Performance",
        "cfg_sec_paths":    "Game paths",
        "cfg_sec_versions": "Visible versions in launcher",
        "cfg_sec_lang":     "Language / Idioma",
        "cfg_username":     "Username",
        "cfg_username_h":   "Name shown in-game",
        "cfg_rammin":       "Min RAM",
        "cfg_rammin_h":     "e.g. 512M, 1G",
        "cfg_rammax":       "Max RAM",
        "cfg_rammax_h":     "e.g. 2G, 4G, 8G",
        "cfg_java":         "Java path",
        "cfg_java_h":       "Leave empty for auto-detection",
        "cfg_gamedir":      "Minecraft directory",
        "cfg_gamedir_h":    "Folder where versions are installed",
        "cfg_browse":       " Browse ",
        "cfg_save":         "Save changes",
        "cfg_saved_title":  "Saved",
        "cfg_saved_msg":    "Settings saved successfully.",
        "cfg_warn_restart": "Restart the launcher to apply the new language.",
        "cfg_activated":    "Enabled",
        "cfg_deactivated":  "Disabled",
        "cfg_offline_warn": "For Microsoft accounts use the official Mojang launcher.",
        "cfg_show_rel":     "Releases",
        "cfg_show_rel_s":   "Official stable versions",
        "cfg_show_snap":    "Snapshots",
        "cfg_show_snap_s":  "Development builds",
        "cfg_show_beta":    "Betas",
        "cfg_show_beta_s":  "Old beta versions",
        "cfg_show_alph":    "Alphas",
        "cfg_show_alph_s":  "Old alpha versions",

        # About tab
        "about_subtitle":   "Unofficial Minecraft Java Edition Launcher",
        "about_version":    "Version 2.0  |  Python + minecraft-launcher-lib",
        "about_f1_t":       "Versions",
        "about_f1_d":       "Release, Snapshot\nBeta & Alpha",
        "about_f2_t":       "Downloads",
        "about_f2_d":       "Assets & libraries\nauto from Mojang",
        "about_f3_t":       "RAM",
        "about_f3_d":       "Fully\nconfigurable",
        "about_f4_t":       "Java",
        "about_f4_d":       "Auto\ndetection",
        "about_disclaimer": "Not affiliated with Mojang Studios or Microsoft Corporation.",
    },
}

def get(key: str, lang: str = "es", **kwargs) -> str:
    text = STRINGS.get(lang, STRINGS["es"]).get(key, key)
    if kwargs:
        text = text.format(**kwargs)
    return text
